### PR TITLE
Updated twitter icon 

### PR DESCRIPTION
**Pull request by varunpareek690**
Summary:
This pull request includes several changes to the project, primarily focusing on visual improvements, content alignment, and added functionality.

Fixes:
#30 
#23 

Changes Made:

Twitter Logo Update:

Replaced the old Twitter logo with a new, updated version for a fresher look and consistency with the latest branding.

Self-Description Alignment:
Adjusted the alignment of the self-description section to be justified, providing a more polished and visually appealing appearance.
Section Opening in New Page:
Modified the code to make the "View Project and View Code" open in a new browser tab when clicked, enhancing the user experience and maintaining better navigation.

Blog Section Addition in the More Tab:
Added a new "Blog" section to the project, providing a platform for sharing articles and news.
Screenshots (if applicable):
image

Blog Page
image

Additional Notes:

Please review and provide feedback on the changes made.
and if satisfied please assign this PR with "hactoberfest-accepted" label as I have tried to do my best and intend to do more such contributions in the repo again
So I again request you to review the changes and assign the PR with "HACKTOBERFEST-ACCEPTED" label!
This PR is related to issue #30 and #23 , as mentioned above.

### CODE REVIEW

**Comment by soniyaprasad77** [comment]
Sure, feel free to proceed. I'd appreciate it if you could incorporate a blog section with a unique style that aligns seamlessly with the website's theme. You're welcome to explore my articles on [Hashnode](https://soniyaprasad.hashnode.dev/) for inspiration, and then adapt the blog section accordingly. Please provide a brief description of the first paragraph of each article, and include a link to the full post in the 'Read More' section.

**Comment by varunpareek690** [comment]
I assure you that I will make the necessary modifications as soon as possible. Thank you for assigning the PR.

**Comment by varunpareek690** [comment]
Hi, ma'am Just wanted to ask a thing being a newbie I do not have ample knowledge to make a "cards" format blog. Though I do not intend to disappoint you in any way, will it be okay if I correct the read more or read less issue, if you say no I will learn and then make the cards but I surely intend to complete the task!

**Comment by soniyaprasad77** [comment]
No worry, you can contribute whatever suits you well. 😊

**Comment by varunpareek690** [comment]
Thank You So much ma'am for being so kind and understanding I have committed the changes, so now if you may assign the hacktoberfest label. Also I will not give up easily I will learn more and give you the actual changes you need!
Thank You!
Varun

**Comment by soniyaprasad77** [comment]
please remove the blog section, just go with changing only twitter icon, i will merge it

**Comment by varunpareek690** [comment]
Doing it right away ma'am

**Comment by varunpareek690** [comment]
Done ma'am

**Comment by soniyaprasad77** [comment]
I cant find your code for twitter icon in this in commit. can you commit again with replacement of twitter icon?

**Comment by soniyaprasad77** [comment]
Amazing, Thankyou so much for your valuable contribution. @varunpareek690

**Pull request merged**
